FLAGS = -Wall -pedantic -lgmp

factorial:
	clear
	gcc $(FLAGS) -o test_factorial test_factorial.c
	./test_factorial

assignment:
	clear
	gcc $(FLAGS) -o test_assignment test_assignment.c
	./test_assignment